version: "3.8"

services:

  db:
    container_name: postgis_db
    image: postgis/postgis:14-3.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}